on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true
      GITHUB_TOKEN:
        required: true

jobs:
  build:

    runs-on: ${{ inputs.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore .NET tools
      run: dotnet tool restore

    - name: Restore dependencies
      run: dotnet restore

    - name: Start Sonar Scanner
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: >
        dotnet dotnet-sonarscanner
        begin
        /k:"RPetras3_SpaceWeather"
        /o:"rpetras3"
        /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
        /d:sonar.host.url="https://sonarcloud.io"
        /d:sonar.cs.opencover.reportsPaths=**/*.opencover.xml

    - name: Build
      run: >
        dotnet build
        --no-restore
        --configuration Release
        --property:Version=${{ inputs.version }}

    - name: Test
      run: >
        dotnet test
        --no-build
        --verbosity normal
        --configuration Release
        --property:Version=${{ inputs.version }}
        --collect "XPlat Code Coverage;Format=opencover"

    - name: End Sonar Scanner
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: >
        dotnet dotnet-sonarscanner
        end
        /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

    - name: Create Dotnet Tool
      working-directory: src/RPetras.SpaceWeatherCLI
      run: >
        dotnet pack
        --no-build
        --no-restore
        --property:PackageVersion=${{ inputs.version }}

    - name: Create Dotnet Tool
      working-directory: src/RPetras.SpaceWeatherLib
      run: >
        dotnet pack
        --no-build
        --no-restore
        --property:PackageVersion=${{ inputs.version }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts-${{ inputs.os }}
        path: |
          **/*.nupkg
          **/*.snupkg
