name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build Artifacts
    uses: ./.github/workflows/build.yml
    with: 
      os: ubuntu-latest
      version: 0.0.0-run.${{ github.run_number }}
    secrets: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
